version: '3'

services:

    app:
        build: .
        container_name: microservice-videos-app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: microservice-videos-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    # db:
    #     build: ./.docker/mysql
    #     container_name: microservice-videos-db
    #     restart: always
    #     tty: true
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./.docker/dbdata:/var/lib/mysql
    #         - ./.docker/mysql:/docker-entrypoint-initdb.d
    #     environment:
    #         - MYSQL_DATABASE=code_micro_videos
    #         - MYSQL_ROOT_PASSWORD=root
    #     networks:
    #         - app-network
    #     command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

    db:
        build: ./.docker/mysql
        # command: --default-authentication-plugin=mysql_native_password
        container_name: microservice-videos-db
        restart: always
        tty: true
        volumes:
            - ./.docker/mysql:/docker-entrypoint-initdb.d
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: code_micro_videos
            MYSQL_USER: www-data
            MYSQL_PASSWORD: root
        ports:
            - 3306:3306
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: microservice-videos-redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
